# This file contains the configuration for the pipeline.

# Model Configuration
MODEL_NAME : "cardiffnlp/twitter-roberta-base-sentiment"
PIPELINE_NAME : "sentiment-analysis"

# Label Mapping (from model card)
LABELS  :
  LABEL_0: 'NEGATIVE'
  LABEL_1: 'NEUTRAL'
  LABEL_2: 'POSITIVE'

LABEL_SCORE_MAP : 
  POSITIVE: 1
  NEUTRAL: 0 
  NEGATIVE: -1

# Filler Word List
FILLER_WORDS :
  - um
  - uh
  - ah
  - er
  - hmm
  - like
  - so
  - well
  - actually
  - basically
  - literally
  - seriously
  - honestly
  - obviously
  - clearly
  - maybe
  - perhaps
  - okay
  - alright
  - right
  - just
  - kinda
  - sorta
  - anyway
  - now
  - then
  - sure
  - yeah
  - nope
  - yup
  - alrighty
  - gee
  - huh
  - whoa
  - really
  - fine
  - okayyy
  - gotcha